# Generated by Django 5.0.7 on 2024-07-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_is_active_alter_task_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_important",
            field=models.BooleanField(
                default=False, verbose_name="Признак важности задачи"
            ),
        ),
    ]
