# Generated by Django 5.0.7 on 2024-08-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_task_is_important"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="owner",
            field=models.TextField(blank=True, null=True, verbose_name="создатель"),
        ),
    ]
